---
- name: Install nginx server on host
  hosts: ubuntu
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present