---
- name: Creating 2 computes in a network
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Create flavor for the compute
      command: microstack.openstack flavor create --public m1.tiny --id auto --ram 512 --disk 1 --vcpus 2 --rxtx-factor 1
      ignore_errors: yes

    - name: Create network
      command: microstack.openstack network create test
      ignore_errors: yes

    - name: Create a subnet and assign to existing network
      command: microstack.openstack subnet create test-subnet --network test --subnet-range 192.0.2.0/24
      ignore_errors: yes

    - name: Create keypair
      command: microstack.openstack keypair create test
      ignore_errors: yes

    - name: Create two servers in given network
      command: microstack.openstack --insecure server create --flavor m1.tiny --image cirros --network test --key-name test --min 2 --max 2 test