---
- name: Creating 2 computes in a network
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Create flavor for the compute
      command: microstack.openstack flavor create --public flavor1 --id auto --ram 256 --disk 25 --vcpus 1 --rxtx-factor 1
      ignore_errors: yes

    - name: Create network
      command: microstack.openstack network create net1
      ignore_errors: yes

    - name: Create a subnet and assign to previous network
      command: microstack.openstack subnet create subnet1 --network net1 --subnet-range 192.0.2.0/24
      ignore_errors: yes

    - name: Create keypair
      command: microstack.openstack keypair create key1
      ignore_errors: yes

    - name: Create two servers in given network
      command: microstack.openstack --insecure server create --flavor flavor1 --image cirros --network net1 --key-name key1 --min 2 --max 2 myhost